#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme                     = "molokai"
# colorscheme_bg                  = "dark"
# Enable vim compatible
vimcompatible                   = true
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors                = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator          = "arrow"
statusline_inactive_separator = "nil"
buffer_index_type             = 4
enable_key_frequency          = true
enable_statusline_bfpath      = true
statusline_left_sections      = ['winnr', 'major mode', 'syntax checking', 'version control info']
enable_tabline_ft_icon        = true
enable_os_fileformat_icon     = true
enable_statusline_mode        = true

enable_vimfiler_filetypeicon  = true
enable_vimfiler_gitstatus     = true
enable_vimfiler_welcome       = false

bootstrap_before              = "myspacevim#before"
bootstrap_after               = "myspacevim#after"


[[custom_plugins]]
name = "takac/vim-hardtime"

# Move word to word with easy
[[custom_plugins]]
name  = 'chaoren/vim-wordmotion'
merge = false

# For toggle comment
[[custom_plugins]]
name  = 'tpope/vim-commentary'
merge = false

# Auto pair
[[custom_plugins]]
name  = 'jiangmiao/auto-pairs'
merge = false

# Add badwolf theme
[[custom_plugins]]
name  = 'sjl/badwolf'
marge = false

# Add auto format
[[custom_plugins]]
name  = 'Chiel92/vim-autoformat'
marge = false

[[custom_plugins]]
name  = 'mbbill/undotree'
marge = false

# Enable autocomplete layer
[[layers]]
name                                = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior    = "smart"

[[layers]]
name             = 'shell'
default_position = 'top'
default_height   = 30

[[layers]]
name = "colorscheme"

[[layers]]
name = "fzf"

[[layers]]
name = 'tools'

[[layers]]
name = "git"

[[layers]]
name = 'VersionControl'

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#vim"
