#! /bin/sh

# Autostart
feh --bg-fill --randomize ~/Pictures/Wallpapers/*.jpg &
$HOME/.config/polybar/launch &
sxhkd &
xsetroot -cursor_name left_ptr &
fcitx &
compton &
xautolock -time 10 -locker i3lock-next &
redshift -l 10.823099:106.629662 &


# Workspace
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Border
bspc config border_width 2

# Gap
bspc config window_gap 15

# Color
bspc config normal_border_color   "#282A36"
bspc config focused_border_color  "#6495ED"
bspc config presel_feedback_color "#BD93F9"

# Monocule
bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config single_monocle     true

# Float
bspc rule -a Lxappearance         state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a mpv                  state=floating
bspc rule -a Pcmanfm              state=floating
bspc rule -a Surf                 state=tiled
bspc rule -a Xarchiver            state=floating
bspc rule -a Zathura              state=tiled

bspc config top_padding         0
bspc config split_ratio         0.52
